### ISSUE TITLE
Does not work with new v3 YouTube API.

### ISSUE THREAD

**Issue by josheverett** [MaxGfeller/youtube-search#12]
Heads up: YouTube has turned off their old API, which has broken this module.

**Comment by MaxGfeller** [comment]
Woot, thanks for pointing that out! Time for a rewrite, i guess

**Comment by josheverett** [comment]
Yup, I had been using your package for my sonos2youtube project. You might find this diff useful:

https://github.com/josheverett/sonos2youtube/commit/0114dcbe2c2287d291e2229f83a197b193995479

I had initially planned to contribute a patch to youtube-search, but the new API is sufficiently different from the old that the path you'd want to take toward v3 could go several ways.

**Comment by MaxGfeller** [comment]
Alright, should be fixed now. I'll let this issue open for now, cause it needs some more documentation. Feel free to give it another try @josheverett
