### ISSUE TITLE
For playlists, the link gets set to something nonsensical

### ISSUE THREAD

**Issue by zuzak** [MaxGfeller/youtube-search#15]
Because there is no `videoId` parameter when getting a playlist from the API, this module sets the `link` property to `https://www.youtube.com/watch?v=undefined`, which is unexpected behaviour.

**Comment by zuzak** [comment]
This can be worked around by setting the options to `{type: "video,channel"}`.

**Comment by SOSANA** [comment]
(crickets) 

this repo not being maintained?

**Comment by MaxGfeller** [comment]
Anyone up for a pull request?

**Comment by frankhale** [comment]
@zuzak, I cannot get your workaround to work for searching for a playlist. If I search for a known playlist given it's ID it will return no results. If I don't specify the 'type' option then I do get results.

I'm attempting to resolve 'undefined' ID and incorrect link and will submit a pull request for this if I get it working.

```
[ { id: undefined,
    link: 'https://www.youtube.com/watch?v=undefined',
    kind: 'youtube#playlist',
    publishedAt: '2012-08-13T15:10:11.000Z',
    channelId: 'UCD2chWdy8F5wljQViVZ9g0Q',
    title: 'Trance',
    description: 'Best Trance Playlist on YouTube. Artists vary from DJ Splash and DJ Satomi to Tiesto. Enjoy the 14 hours of Bliss!',
    thumbnails: { default: [Object], medium: [Object], high: [Object] } } ]
```

**Comment by frankhale** [comment]
Okay here is a proposed fix for this issue, please let me know if this is okay and if so I'll submit a PR for it.

https://gist.github.com/frankhale/385d23384b8e738ff6e18c85a9e0f97b

**Comment by frankhale** [comment]
The pull request I submitted for this back in July was merged so I think this issue can be closed now.
