### ISSUE TITLE
Youtube playlist error

### ISSUE THREAD

**Issue by uditharandika** [MaxGfeller/youtube-search#26]
https://www.youtube.com/playlist&list=PLeTEa8oJjRtt9NNWy1aL9tjVz2KsGGm16
this is a playlist link that i received and its not working, i identified this url need to change like https://www.youtube.com/playlist?list=PLeTEa8oJjRtt9NNWy1aL9tjVz2KsGGm16 this

i replaced " & " with " ? ",& i tried it with many links. please kindly fix this bug.
thank you

**Comment by frankhale** [comment]
So after replacing "&" with "?" did it fix it? Looks like line 85 of index.js is where this issue is, correct? If this fixed it do you mind submitting a pull request?

**Comment by MaxGfeller** [comment]
Thanks for reporting this @uditharandika! The link was assembled wrong here. It's now fixed and released in `1.0.10`

**Comment by uditharandika** [comment]
thanks MaxGfeller ,

**Comment by frankhale** [comment]
Thanks @uditharandika for reporting!
