### ISSUE TITLE
Reoccuring Error

### ISSUE THREAD

**Issue by TacticalTechJay** [MaxGfeller/youtube-search#28]
``const Discord = require("discord.js");
const client = new Discord.Client();
const config = require("./config.json");
const ytdl = require("ytdl-core");
const fs = require("fs");

client.on("ready", () => {
  console.log("Logged in as ${client.user.username}!");
  client.user.setGame("Use >help for commands.");
});

client.on("message", message => {
  var aud = {
    maxResults: 1,
    key: config.YoutubeApiKey
  };

  const search = require("youtube-search");
  if  (message.content.startsWith(config.prefix + "play")) {
    message.delete(2000);
    const voiceChannel = message.member.voiceChannel;
    if(!voiceChannel) return message.reply(" I don't see you peeking in that voice channel :smile:");
    if(!voiceChannel.joinable) return message.reply(" I can not join because I see that the server is full. Or I am not have access to the voice channel called " + voiceChannel +  "");
    voiceChannel.join()
    .then(connection => {
      search (message.content.split(" ").slice(1).join(" "), aud, function (err, results) {
        ytdl(results[0].link, {filter: "audioonly"}).pipe(fs.createWriteStream("${song.title}.mp3"));
        const stream = ytdl(results[0].link, {
          filter: "audioonly"
        });
        if (err) return console.log(err);
        console.log("ERROR: " + err);
        console.log("RESULTS: " + results);
        console.log("RESULTS" + require("util").inspect(results, { depth: null }));
        ytdl.setVolume(1);
        const dispatcher = connection.playStream(stream);
        dispatcher.on("end", () => voiceChannel.leave);
      });
    });
  }});

client.login(config.token);
client.on("error", (e) => console.error(e));
client.on("warn", (e) => console.warn(e));
``
I keep on receiving an error "TypeError: Cannot read property '0' of undefined" and tried to find a way to get a bit more detail and got "ERROR: null" including "RESULTS: [object Object]" Does it have to do with ytdl-core? Or this? I used a sample video "I believe I can fly" to see if it works. The result was [this](https://gyazo.com/434b1bc16f194abe74ad76051b43b08e). The link contains the picture, sadly I wanted to find a way to trim it but found this to get trimmed pictures. Gyazo is the software used to take the trimmed screenshot. Even though this is getting off topic, I just wanted to report this, hope you respond quickly due to me being on a vacation. @MaxGfeller *(this is also posted on the issues page on youtube-search for reassurance.)*

**Comment by frankhale** [comment]
Okay based on your link you got results from 'youtube-search' so I'm not sure where the error is coming from in that snippet. Looks like it uses Discord but I'm not sure looking at your code snippet how to run this in order to test locally.

**Comment by frankhale** [comment]
Additionally it'd be nice if you could post the entire stack trace so we can see exactly what line the error is coming from

**Comment by TacticalTechJay** [comment]
`0|Tactical | RESULTS: [object Object]
0|Tactical | RESULTS[ { id: 'GIQn8pab8Vc',
0|Tactical |     link: 'https://www.youtube.com/watch?v=GIQn8pab8Vc',
0|Tactical |     kind: 'youtube#video',
0|Tactical |     publishedAt: '2013-10-29T02:17:17.000Z',
0|Tactical |     channelId: 'UCZZjtPu39XM1ujnfzooh-ew',
0|Tactical |     channelTitle: 'RKellyVEVO',
0|Tactical |     title: 'R. Kelly - I Believe I Can Fly',
0|Tactical |     description: 'R. Kelly\'s official music video for \'I Believe I Can Fly\'. Click to listen to R. Kelly on Spotify: http://smarturl.it/RKSpot?IQid=RKICF As featured on The Essential R.',
0|Tactical |     thumbnails:
0|Tactical |      { default:
0|Tactical |         { url: 'https://i.ytimg.com/vi/GIQn8pab8Vc/default.jpg',
0|Tactical |           width: 120,
0|Tactical |           height: 90 },
0|Tactical |        medium:
0|Tactical |         { url: 'https://i.ytimg.com/vi/GIQn8pab8Vc/mqdefault.jpg',
0|Tactical |           width: 320,
0|Tactical |           height: 180 },
0|Tactical |        high:
0|Tactical |         { url: 'https://i.ytimg.com/vi/GIQn8pab8Vc/hqdefault.jpg',
0|Tactical |           width: 480,
0|Tactical |           height: 360 } } } ]
0|Tactical | TypeError: Cannot read property '0' of undefined
0|Tactical |     at C:\Users\CESNORED\Documents\Bot\tac-bot.js:54:21
0|Tactical |     at Request._callback (C:\Users\CENSORED\Documents\Bot\node_modules\youtube-search\index.js:109:14)
0|Tactical |     at Request.self.callback (C:\Users\CENSORED\Documents\Bot\node_modules\request\request.js:188:22)
0|Tactical |     at emitTwo (events.js:106:13)
0|Tactical |     at Request.emit (events.js:194:7)
0|Tactical |     at Request.<anonymous> (C:\Users\CENSORED\Documents\Bot\node_modules\request\request.js:1171:10)
0|Tactical |     at emitOne (events.js:96:13)
0|Tactical |     at Request.emit (events.js:191:7)
0|Tactical |     at IncomingMessage.<anonymous> (C:\Users\CENSORED\Documents\Bot\node_modules\request\request.js:1091:12)
0|Tactical |     at Object.onceWrapper (events.js:293:19)`

**Comment by TacticalTechJay** [comment]
^ That is the entire error message

**Comment by TacticalTechJay** [comment]
The below comment is telling a lie

**Comment by TacticalTechJay** [comment]
The above comment is telling the truth

**Comment by frankhale** [comment]
You are getting results from `youtube-search` so it doesn't appear like there is an error with this module. I did notice one thing though, you are trying to do stuff with the results of the search before you've checked to see if there is an error.

I'd make one modification to this and that is the placement of the if(err) check

```javascript
search(message.content.split(" ").slice(1).join(" "), aud, function(err, results) {
  if (err) return console.log(err);

  // Do stuff here
});
```

Additionally the following line may be failing in your code because message.content may not contain anything but you are trying to split it and then slice it and then join it? Again I don't know because I don't know what the larger picture is with this particular code. It'd be nice to have a way to run it in order to test locally but it appears as though `youtube-search` is not at fault because you do indeed get results from your stack trace.

```
message.content.split(" ").slice(1).join(" ")
```

**Comment by frankhale** [comment]
@TacticalTechJay did you find out where the issue was?

**Comment by TacticalTechJay** [comment]
@frankhale I have have had it caught an error unless it is not. It was `ERROR: null`. I think it may not be an error but I do indeed think it was an error because my bot was stopped. I use some sort of program/command line to run my bot and have it get restarted if it got errors and get restarted.

**Comment by TacticalTechJay** [comment]
I have fixed it, I used node instead of the other program to let it work.
