### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by FireController1847** [MaxGfeller/youtube-search#31]
Does this library support promises? If not, it'd be a great feature to add!

**Comment by MaxGfeller** [comment]
It does not right now but i agree that it would be a great thing to add! PRs welcome :)

**Comment by denizdogan** [comment]
Maybe you already know this, if you want to use promises, you can install `bluebird` and do `const promiseSearch = Promise.promisify(search)` without any issues, check [this example](https://github.com/denizdogan/nima/commit/e81a06b62045977ef619df2cf89f8cd9f1fd74f3#diff-5bc1da1d61cd96baff1eaac7f1dee292R6).

**Comment by FireController1847** [comment]
I understand, but the PR makes it easier for everyone to use promises instead of having to use workarounds like Util.Promisify.

**Comment by frankhale** [comment]
It's too bad this was closed. Where is @MaxGfeller?

**Comment by FireController1847** [comment]
No sure, I've just found promisify will work for now.
