### ISSUE TITLE
I'm trying to make a discord bot and I'm trying to retrieve the url

### ISSUE THREAD

**Issue by warbrine** [MaxGfeller/youtube-search#34]
When I set results.url to a variable it comes back undefined

**Comment by warbrine** [comment]
I saw the other guys closed issue but idk how he resolved it.

**Comment by frankhale** [comment]
I will take a look at this one in the morning and see if we can figure it out

**Comment by MaxGfeller** [comment]
Umm, i don't really know what you're trying to do without a code sample or anything but it sounds like `results` is an array.

Tip: just inspect what `results` looks like using `console.log`

**Comment by frankhale** [comment]
@warbrine did you figure out your problem?

question, why are you setting requests.url?

**Comment by warbrine** [comment]
Yes I did find the issues solution and lengths that for you @frankhale

**Comment by warbrine** [comment]
Oops typing from my phone, leme grab you the fix I found.

**Comment by KidOfEpicness** [comment]
It's link, not url
