### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by durja** [MaxGfeller/youtube-search#35]
Module not found: Error: Cannot resolve module 'net' in /Users/arai/desktop/React/myproject/node_modules/tough-cookie/lib

**Comment by MaxGfeller** [comment]
Hi @durja, sorry for the late response. Does the error still occur?

**Comment by PJCHENder** [comment]
I face the same issue.
It seems that the dependency,`tough-cookie`, can not resolve module 'net'.

---
```
ERROR in ./~/tough-cookie/package.json
Module parse failed: /Users/pjchen/Projects/Tutorial/Udemy/ModernReactAndRedux/ReduxSimpleStarter/node_modules/tough-cookie/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
```

**Comment by MaxGfeller** [comment]
We recently replaced the http client and are now using `axios`. This problem should no longer occur.

Feel free to reopen if it does.
