### ISSUE TITLE
Exposed key in tests/test-search.js

### ISSUE THREAD

**Issue by rokoburilo** [MaxGfeller/youtube-search#45]
Don't know if it's fake or real, but just as a heads up.

**Comment by MaxGfeller** [comment]
Thanks for letting me know @rokoburilo! The key is just used for the automated tests and nothing else. But still - it makes no sense in exposing it.

I just changed this behavior in https://github.com/MaxGfeller/youtube-search/commit/1b10f72b336223ef79dd0537b09da16fd8a10e2c and added the key as a secret to Travis.
