### ISSUE TITLE
Search fails while more than one word

### ISSUE THREAD

**Issue by mbpictures** [MaxGfeller/youtube-search#50]
Hello!
First thank you for your module, but I ensurred an issue, where the search fails when the query contains more than one word seperated by space. For example:
Works: "video", "kurzgesagt", etc.
Doesn't work: "best videos"

Do you have a fix for that? I tried to replace the space with a '+', '|' or '%20' but nothing actually worked.

**Comment by MaxGfeller** [comment]
Hi @mbpictures!

Thanks for the report. I cannot reproduce this and i just added a test to check for this in https://github.com/MaxGfeller/youtube-search/commit/ec53dd6767106c315e58624a3960a71d713c3c38.

Which version of the library do you use? And do you use it in the browser or from node?

**Comment by mbpictures** [comment]
Well, that was fast :D. I use it from node.js in combination with amazons alexa-sdk. It works fine to get the Searchquery entered by the user, but the "err" variable is set to true in the callback function of your search function

**Comment by MaxGfeller** [comment]
And what is the error message? Could you maybe create a reproducable example?

**Comment by mbpictures** [comment]
I actually found out, that the problem is not the search... it is the "youtube-stream-url" module where i get the plane video url from... Sorry for wasting your time! :(

**Comment by MaxGfeller** [comment]
No problem, i'm glad you could resolve it :)
