### ISSUE TITLE
error 403 

### ISSUE THREAD

**Issue by theofaucher** [MaxGfeller/youtube-search#60]
Hi,

I would like to use your module but unfortunately I have an error: Error: Request failed with status code 403, I see where this could come from, I took your example program in javascript. Can you help me ?

Thank you in advance,
Theo

**Comment by batgo6o** [comment]
Have the same problem

**Comment by batgo6o** [comment]
Hi, this issues comes from the Youtube API key itself. Workaround is to make a new project or generate a new key

**Comment by Weshhhh** [comment]
Hi, same error, tried to change everything, api key from multiple accounts, New project etc... and still getting this error :(

**Comment by batgo6o** [comment]
can I see your code and its output?

**Comment by exogenesys** [comment]
Any updates on this? I've having the same issue.

`const options: youtubeSearch.YouTubeSearchOptions = {
  maxResults: 10,
  key: "API_KEY",
};
`

`const execute = async (
  searchTerm: string
): Promise<ListOfLinksResponseType> => {
  return new Promise((resolve, reject) => {
    youtubeSearch.default(searchTerm, options, (err, res) => {
      if (err) return reject({ err, success: false });
      return resolve({
        data: transformResponse(res),
        success: true,
      });
    });
  });
};
`

**Comment by exogenesys** [comment]
@theofaucher Could you resolve this? Did you find any better resource which helped you?

**Comment by batgo6o** [comment]
It's because the API key is messing up or something

**Comment by MaxGfeller** [comment]
It seems like there might be a problem with the API keys for the Youtube Data API  v3. You can try running the following:

```bash
curl https://www.googleapis.com/youtube/v3/search\?key\=<your_key>\&part\=snippet --header 'Accept: application/json'
```

nd check for the error response. Maybe you'll have to generate a new API token.

**Comment by exogenesys** [comment]
Running,

`curl https://www.googleapis.com/youtube/v3/search\?key\=<your_key>\&part\=snippet --header 'Accept: application/json'`

I get this reply,

```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

Even if I generate a new key, I get this. I tried restricting the key to just YouTube Data API v3, but that's didn't help either. 😞

**Comment by MaxGfeller** [comment]
@exogenesys Have you tried creating a new app?

I'll close this issue for now as it's unrelated to this library, but feel free to continue the discussion.
