### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Only-Moon** [MaxGfeller/youtube-search#73]
```js
const searchOptions = { maxResults: 1, key: apiKey, type: 'video', safeSearch: "strict"};
```

Its still showing nsfw videos

**Comment by Only-Moon** [comment]
Full code, as you dont have a support
```js
const { CommandInteraction, MessageEmbed } = require("discord.js");
const he = require('he');
const search = require('youtube-search');

module.exports = {
    name: "youtube-search",
    description: "Search youtube for a specific text provided",
    ownerOnly: false,
    options: [
        {
            type: 'STRING',
            description: 'name of video',
            name: 'video',
            required: true,
        },
    ],
    userperm: [""],
    botperm: [""],
    /**
     *
     * @param {CommandInteraction} interaction
     * @param {String[]} args
     */
    run: async (bot, interaction, args) => {
    const apiKey = process.env.YT_KEY
    const videoName = args.join(' ');

    if (!videoName) return interaction.editReply(`${emoji.Error} Please provide a YouTube video name`);

    const searchOptions = { maxResults: 1, key: apiKey, type: 'video', safeSearch: "strict"};

    let result = await search(videoName, searchOptions)
      .catch(err => {
        return interaction.editReply(`${bot.error} Please try again in a few seconds`);
      });

    result = result.results[0];
    if (!result) 
    return interaction.editReply(`${bot.error} Unable to find **${videoName}**, please try a different YT Title`);

    const decodedTitle = he.decode(result.title);
    const embed = new MessageEmbed()
    .setTitle(decodedTitle)
    .setURL(result.link)
    .setThumbnail('https://cdn1.iconfinder.com/data/icons/logotypes/32/youtube-512.png')
    .setDescription(result.description)
    .setFooter(`${interaction.user.username}`, interaction.user.avatarURL({ dynamic: true }))
    .setImage(result.thumbnails.high.url)
    .setTimestamp()
    .setColor(bot.color)

    interaction.editReply({ embeds: [ embed ] })
  }
}
```

**Comment by Shadowblazer93** [comment]
```js
safeSearch: 'strict'
```

Replace the `""` with `''`

The correct syntax would be:
```js
 const searchOptions = { maxResults: 1, key: apiKey, type: 'video', safeSearch: 'strict'};
 ```

**Comment by Only-Moon** [comment]
Oky thanks, I'll try

**Comment by Only-Moon** [comment]
Nope still shows nsfw stuff

**Comment by Shadowblazer93** [comment]
Make sure to go into the video and check if it is age-restricted.
Sometimes youtube is dumb and doesn't age-restrict videos.

If you want, [here is my code](https://paste.gg/p/anonymous/98486e60b8794a899c42462e02c75586) which works flawlessly
(you may need to change some stuff since your setup is a little different)

**Comment by Only-Moon** [comment]
Oky thanks for clearing, so this safefilter only restricts age restricted videoes??

**Comment by Shadowblazer93** [comment]
Yes.
Also, if you want extra security you can blacklist words from the search.

**Comment by Only-Moon** [comment]
> Yes. Also, if you want extra security you can blacklist words from the search.

Can you show an example

**Comment by Shadowblazer93** [comment]
Since it doesn't look like there's an option for that built in yt-search,
you can use [bad-words-npm](https://www.npmjs.com/package/bad-words)

It will replace all bad words specified with **
(or whatever you want to set the placeholder to)

**Comment by Only-Moon** [comment]
> Since it doesn't look like there's an option for that built in yt-search,
> you can use [bad-words-npm](https://www.npmjs.com/package/bad-words)
> 
> It will replace all bad words specified with **
> (or whatever you want to set the placeholder to)

The thing you specified will replace bad word with  ** but i want it to check bad words and return "dont use bad words or something" . I got the idea how to do so.
